// <auto-generated />
using BookSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSystem.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241017070858_Init-Book")]
    partial class InitBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<string>("BooksBookTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Genresid")
                        .HasColumnType("int");

                    b.HasKey("BooksBookTitle", "Genresid");

                    b.HasIndex("Genresid");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("BookSystem.DomainModels.Book", b =>
                {
                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookPages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CoverImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("BookTitle");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookSystem.DomainModels.Book+Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BookSystem.DomainModels.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSystem.DomainModels.Book+Genre", null)
                        .WithMany()
                        .HasForeignKey("Genresid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
